Repository Apptive-Game-Team/WordOnlineClient, pull requests merged in 2025-09, with the labels that each got.

#75 Fix/56
  Assets/Resources/Prefabs/WindExplode.prefab
  Assets/Resources/Prefabs/WindExplode.prefab.meta
  Assets/Resources/Prefabs/WindShot.prefab
  Assets/Resources/Prefabs/WindShot.prefab.meta
  Assets/Resources/Prefabs/WindSlime.prefab
  Assets/Resources/Prefabs/WindSlime.prefab.meta
  Assets/Resources/Prefabs/WindSummon.prefab
  Assets/Resources/Prefabs/WindSummon.prefab.meta
  Assets/Script/Data/LocalMagicData.cs
  Assets/Script/GameScene/GameSceneUIController.cs
  Assets/Script/LobbyScene/EnqueueButton.cs
  Assets/Script/LobbyScene/LobbyUIController.cs
  Assets/Script/LobbyScene/StatusTracker.cs
  Assets/Script/LobbyScene/StatusTracker.cs.meta
  Assets/Script/LobbyScene/UserInfoGetter.cs
  Assets/Script/RegisterScene/RegisterButton.cs
  Assets/Script/StompConnector.cs
Labels: bug, feature

#84 feat: add card mana display and update UI elements for card management
  Assets/Prefabs/CardImage.prefab
  Assets/Prefabs/CardInDeck.prefab
  Assets/Prefabs/HaveCard.prefab
  Assets/Resources/UI/Card/CardImageMapper.asset
  Assets/Resources/UI/Card/magic_build.png
  Assets/Resources/UI/Card/magic_build.png.meta
  Assets/Resources/UI/Card/magic_explode.png
  Assets/Resources/UI/Card/magic_shoot.png
  Assets/Resources/UI/Card/magic_spawn.png
  Assets/Resources/UI/Card/magic_summon.png
  Assets/Resources/UI/Card/type_fire.png
  Assets/Resources/UI/Card/type_leaf.png
  Assets/Resources/UI/Card/type_lightning.png
  Assets/Resources/UI/Card/type_lightning.png.meta
  Assets/Resources/UI/Card/type_ligthning.png
  Assets/Resources/UI/Card/type_nature.png
  Assets/Resources/UI/Card/type_nature.png.meta
  Assets/Resources/UI/Card/type_rock.png
  Assets/Resources/UI/Card/type_water.png
  Assets/Resources/UI/Card/type_wind.png
  Assets/Resources/UI/Card/type_wind.png.meta
  Assets/Resources/UI/magic_card 1.png
  Assets/Resources/UI/magic_card 1.png.meta
  Assets/Resources/UI/type_card 1.png
  Assets/Resources/UI/type_card 1.png.meta
  Assets/Script/DeckScene/CardItemUI.cs
  Assets/Script/GameScene/CardUI.cs
  Assets/Script/GameScene/GameSceneUIController.cs
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: feature

#86 Feature/76
  Assets/Resources/AI/build/anti_air_turret.png
  Assets/Resources/AI/build/anti_air_turret.png.meta
  Assets/Resources/AI/spawn.meta
  Assets/Resources/AI/spawn/thunder_spirit.png
  Assets/Resources/AI/spawn/thunder_spirit.png.meta
  Assets/Resources/Prefabs/ThunderSpirit.prefab
  Assets/Resources/Prefabs/ThunderSpirit.prefab.meta
  Assets/Scenes/GameScene.unity
  Assets/Scenes/TEST_DOTween.meta
  Assets/Scenes/TEST_DOTween/DOTweenTestScene.unity
  Assets/Scenes/TEST_DOTween/DOTweenTestScene.unity.meta
  Assets/Script/DOTweenFeedbackTester.cs
  Assets/Script/DOTweenFeedbackTester.cs.meta
  Assets/Script/GameScene/CardUI.cs
  Assets/Script/GameScene/DOTweenAction.cs
  Assets/Script/GameScene/DOTweenAction.cs.meta
  Assets/Script/GameScene/FieldSelector.cs
  Assets/Script/GameScene/ObjectSpawner.cs
  Assets/Script/GameScene/PlayerAnimationTrigger.cs
  Assets/Script/GameScene/PlayerFeedbackController.cs
  Assets/Script/GameScene/PlayerFeedbackController.cs.meta
  Assets/Script/GameScene/ServedObject.cs
  Assets/Script/GameScene/ZVisualizer.cs
Labels: feature

#88 Feature/87
  Assets/Script/Data/LocalCombinedMagicData.cs
  Assets/Script/Data/LocalCombinedMagicData.cs.meta
Labels: feature

#93 feat: add new prefab and meta files for game assets
  Assets/Resources/Game/build/mana_well.png
  Assets/Resources/Game/build/mana_well.png.meta
  Assets/Resources/Game/spawn/aqua_archer.png
  Assets/Resources/Game/spawn/aqua_archer.png.meta
  Assets/Resources/Game/spawn/rock_golem.png
  Assets/Resources/Game/spawn/rock_golem.png.meta
  Assets/Resources/Game/spawn/storm_rider.png
  Assets/Resources/Game/spawn/storm_rider.png.meta
  Assets/Resources/Prefabs/AquaArcher.prefab
  Assets/Resources/Prefabs/AquaArcher.prefab.meta
  Assets/Resources/Prefabs/ManaWell.prefab
  Assets/Resources/Prefabs/ManaWell.prefab.meta
  Assets/Resources/Prefabs/RockGolem.prefab
  Assets/Resources/Prefabs/RockGolem.prefab.meta
  Assets/Resources/Prefabs/StormRider.prefab
  Assets/Resources/Prefabs/StormRider.prefab.meta
Labels: feature

#103 Feature/102
  Assets/Plugins/WebGL/StompPlugin.jslib
  Assets/Prefabs/LoadingPage.prefab
  Assets/Prefabs/LoadingPage.prefab.meta
  Assets/Scenes/GameScene.unity
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/LoginScene.unity
  Assets/Scenes/MagicBookScene.unity
  Assets/Scenes/ManageDeckScene.unity
  Assets/Scenes/RegisterScene.unity
  Assets/Scenes/ResultScene.unity
  Assets/Script/CardInputSender.cs
  Assets/Script/DeckScene/DeckManagementController.cs
  Assets/Script/GameScene/BarController.cs
  Assets/Script/GameScene/MagicCombineButton.cs
  Assets/Script/GameScene/MagicCombineButton.cs.meta
  Assets/Script/LoadingPage.cs
  Assets/Script/LoadingPage.cs.meta
  Assets/Script/LobbyScene/EnqueueButton.cs
  Assets/Script/LobbyScene/LobbyUIController.cs
  Assets/Script/LobbyScene/StatusTracker.cs
  Assets/Script/LoginScene/LoginButton.cs
  Assets/Script/RegisterScene/RegisterButton.cs
  Assets/Script/StompConnector.cs
Labels: feature

#108 Fix/105
  Assets/Scenes/GameScene.unity
  Assets/Script/Data/CreatedObjectDto.cs
  Assets/Script/Data/UpdatedObjectDto.cs
  Assets/Script/GameScene/RejoinSyncHelper.cs
  Assets/Script/GameScene/RejoinSyncHelper.cs.meta
  Assets/Script/LobbyScene/StatusTracker.cs
  Assets/Script/SceneContext.cs
  Assets/Script/StompConnector.cs
Labels: bug
